Add OHCI and UHCI drivers to initrd.
USB smart card readers are most full speed devices, and there is no
"rate-matching hubs" beneath the root hub on older (e.g. GM45) plat-
forms, which has emulated OHCI or UHCI interfaces and needs correspon-
ding drivers to communicate with card readers directly plugged into
the motherboard, otherwise a discrete USB hub should be inserted be-
tween the motherboard and the reader.

Tested on my x200s.

diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -68,22 +68,20 @@ confirm_totp()
 	echo
 }
 
-confirm_gpg_card()
+enable_usb()
 {
-	read \
-		-n 1 \
-		-p "Please confirm that your GPG card is inserted [Y/n]: " \
-		card_confirm
-	echo
-
-	if [ "$card_confirm" != "y" \
-		-a "$card_confirm" != "Y" \
-		-a -n "$card_confirm" ] \
-	; then
-		die "gpg card not confirmed"
+	if ! lsmod | grep -q uhci_hcd; then
+		insmod /lib/modules/uhci-hcd.ko \
+		|| die "ehci_hcd: module load failed"
 	fi
-
-	# setup the USB so we can reach the GPG card
+	if ! lsmod | grep -q ohci_hcd; then
+		insmod /lib/modules/ohci-hcd.ko \
+		|| die "ehci_hcd: module load failed"
+	fi
+	if ! lsmod | grep -q ohci_pci; then
+		insmod /lib/modules/ohci-pci.ko \
+		|| die "ehci_pci: module load failed"
+	fi
 	if ! lsmod | grep -q ehci_hcd; then
 		insmod /lib/modules/ehci-hcd.ko \
 		|| die "ehci_hcd: module load failed"
@@ -101,6 +99,25 @@ confirm_gpg_card()
 		|| die "ehci_pci: module load failed"
 		sleep 2
 	fi
+}
+
+confirm_gpg_card()
+{
+	read \
+		-n 1 \
+		-p "Please confirm that your GPG card is inserted [Y/n]: " \
+		card_confirm
+	echo
+
+	if [ "$card_confirm" != "y" \
+		-a "$card_confirm" != "Y" \
+		-a -n "$card_confirm" ] \
+	; then
+		die "gpg card not confirmed"
+	fi
+
+	# setup the USB so we can reach the GPG card
+	enable_usb
 
 	gpg --card-status \
 	|| die "gpg card read failed"
